### ISSUE TITLE
Add option to not fail the healthcheck response for certain dependencies

### ISSUE THREAD

**Issue by karthikmuralidharan** [etherlabsio/healthcheck#2]
By default, any error occurring in the checker responses leads to a `503` HTTP status code. But we may not want to fail the healthcheck in case certain dependencies fail (eg: metrics service, s3 etc) but would like to observe the errors in the response for taking further action.

**Comment by sponomarev** [comment]
Hi, @karthikmuralidharan! I'll take care.
